EXPERIMENT_NAME: 'dhg28_full-model'
INPUT:
  NUM_WORKERS: 8
MODEL:
  FUSION_TYPE: 'early_fusion'
  INPUT_COMBINATION: 'local_global'
  LOCAL_BACKBONE: 'dgcnn'
  LOCAL_EMBED: 512
  GLOBAL_BACKBONE: 'bps'
  GLOBAL_EMBED: 1024
  NUM_CLASSES: 28
  BPS_DENSENET:
    NUM_BPS_POINTS: 256
    RANDOM_SEED: 21
DATASETS:
  NAME: 'dhg'
  CV_SUBJECT_IDS: [[1,],[2,],[3,],[4,],[5,],[6,],[7,],[8,],[9,],[10,],[11,],[12,],[13,],[14,],[15,],[16,],[17,],[18,],[19,],[20,],]
  DHG:
    PROCESS_FOLDER: 'dbscanCluster_numPts=512'
    NUM_CLASSES: 28
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.005
  BATCH_SIZE_TRAIN: 8
  BATCH_SIZE_TEST: 8
  NUM_EPOCHS: 100
  LR_MILESTONES: [50, 80, 90]
  WEIGHT_NOISE: 0.02