from yacs.config import CfgNode as CN

_C = CN()

_C.BASE_DIRECTORY = "../results"
_C.EXPERIMENT_NAME = ""

_C.INPUT = CN()
_C.INPUT.NUM_WORKERS = 8

_C.DATASETS = CN()
_C.DATASETS.NAME = 'shrec17'
_C.DATASETS.FILE_LIST_TRAIN = 'train_gestures.txt'
_C.DATASETS.FILE_LIST_VAL = 'val_gestures.txt'
_C.DATASETS.FILE_LIST_TEST = 'test_gestures.txt'
_C.DATASETS.CV_SUBJECT_IDS = []

_C.DATASETS.SHREC = CN()
_C.DATASETS.SHREC.PROCESS_FOLDER = 'dbscanCluster_numPts=512'
_C.DATASETS.SHREC.NUM_CLASSES = 28

_C.DATASETS.DHG = CN()
_C.DATASETS.DHG.PROCESS_FOLDER = 'dbscanCluster_numPts=512'
_C.DATASETS.DHG.NUM_CLASSES = 28

_C.MODEL = CN()
_C.MODEL.DEVICE = "cuda"
_C.MODEL.NUM_CLASSES = 28
_C.MODEL.INPUT_COMBINATION = 'local_global'
_C.MODEL.FUSION_TYPE = 'early_fusion'
_C.MODEL.LOCAL_BACKBONE = 'dgcnn'
_C.MODEL.GLOBAL_BACKBONE = 'bps'
_C.MODEL.GLOBAL_EMBED = 1024
_C.MODEL.LOCAL_EMBED = 512
_C.MODEL.GLOBAL_SCALER = 600.
_C.MODEL.LOCAL_SCALER = 400.
_C.MODEL.NUM_TIMESTEPS_PER_PRED = 8

_C.MODEL.DGCNN = CN()
_C.MODEL.DGCNN.K = 16
_C.MODEL.DGCNN.EMB_DIMS = 1024

_C.MODEL.BPS_DENSENET = CN()
_C.MODEL.BPS_DENSENET.NUM_BPS_POINTS = 256
_C.MODEL.BPS_DENSENET.RANDOM_SEED = 21


_C.SOLVER = CN()
_C.SOLVER.BASE_LR = 0.0001
_C.SOLVER.WEIGHT_DECAY = 0.005
_C.SOLVER.LR_MILESTONES = [50, 80, 90]
_C.SOLVER.LR_GAMMA = 0.1
_C.SOLVER.NUM_EPOCHS = 100
_C.SOLVER.BATCH_SIZE_TRAIN = 8
_C.SOLVER.BATCH_SIZE_TEST = 8
_C.SOLVER.WEIGHT_NOISE = 0.02
_C.SOLVER.LOSS_FUNCTION = 'cross_entropy'

def get_cfg_defaults():
    return _C.clone()